//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedbackForm
{


    public partial class QuizForm
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.RadioButtonList q1;
        protected System.Web.UI.WebControls.RadioButtonList q2;
        protected System.Web.UI.WebControls.RadioButtonList q3;
        protected System.Web.UI.WebControls.RadioButtonList q4;
        protected System.Web.UI.WebControls.RadioButtonList q5;
        protected System.Web.UI.WebControls.RadioButtonList q6;
        protected System.Web.UI.WebControls.RadioButtonList q7;
        protected System.Web.UI.WebControls.RadioButtonList q8;
        protected System.Web.UI.WebControls.RadioButtonList q9;
        protected System.Web.UI.WebControls.RadioButtonList q10;
        protected System.Web.UI.WebControls.Label lblScore;
        protected System.Web.UI.WebControls.HyperLink lnkFeedback;


    }
}
